
logging:
  level:
    root: info

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db0527?characterEncoding=UTF-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10



